version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      TZ: Asia/Seoul
    volumes:
      - ./data/mysql/:/var/lib/mysql
