# enable / disable
management:
  endpoint:
    health:
      enabled: true
#      show-components: always
      show-details: always
    beans:
      enabled: false
    caches:
      enabled: true
    heapdump:
      enabled: true


  # expose
  endpoints:
    web:
      exposure:
        include: "*"
        # exclude ? include ?? ???? ??
        exclude:
          - beans
      # CORS ??
      cors:
        allowed-origins: http://localhost:8080, http://localhost, http:test.com
        allowed-methods: GET

