# enable / disable
management:
  endpoint:
    health:
      enabled: true
#      show-components: always
      show-details: always
    beans:
      enabled: false
    caches:
      enabled: true
    heapdump:
      enabled: true

    env:
      show-values: when_authorized


  info:
    env:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: simple # full
    os:
      enabled: true



  # expose
  endpoints:
    web:
      exposure:
        include: "*"
        # exclude ? include ?? ???? ??
        exclude:
          - beans
      # CORS ??
      cors:
        allowed-origins: http://localhost:8080, http://localhost, http:test.com
        allowed-methods: GET

