# enable / disable
management:
  endpoint:
    health:
      enabled: false
    beans:
      enabled: false
    caches:
      enabled: true
    heapdump:
      enabled: true


  # expose
  endpoints:
    web:
      exposure:
        include: "*"
        # exclude ? include ?? ???? ??
        exclude:
          - health
          - beans
      # CORS ??
      cors:
        allowed-origins: http://localhost, http:test.com
        allowed-methods: GET