spring:
  cache:
    redis:
      cache-null-values: true
      time-to-live: 40000
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306;database=springredisdb;
    username: uSern@me
    password: p@ssw0rd
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
