spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: passw@rd

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        Type: TRACE
